### ISSUE TITLE
Support tunnelbroker.net (HE)

### ISSUE THREAD

**Issue by jbbr** [pelzvieh/IPv6Droid#33]
It would be great to have support for tunnels by Hurricane Electric / [tunnelbroker.net](https://tunnelbroker.net/)
They offer free tunnels with selectable tunnelservers but no TIC server/AYIYA support.
Changing the endpoint IPv4 is possible with a simple http request (similar to dyndns services).

**Comment by pelzvieh** [comment]
The problem with the protocol used by HE is the following: the IPv4 endpoint must be reachable for protocol 41 packets. In contrast to this, AYIYA requires only a working UDP communication. Mobile networks do not even offer an individual IPv4 address to all devices, devices are not addressable on IP level and therefore not reachable.
