### ISSUE TITLE
No tunnel list is displayed

### ISSUE THREAD

**Issue by quite** [pelzvieh/IPv6Droid#37]
Just trying this for the first time. Set my credentials and try to start the tunnel. I'm getting no list of tunnels (I have two on my account, each with a routed subnet), but this error notification:

    class de.flyingsnail.ipv6droid.ayiya.ConnectionFai..
    You must select a tunnel from list

**Comment by pelzvieh** [comment]
This should be fixed in the current alpha release. You might want to try out:
- join group IPv6Droid on Google+
- join the alpha testing group via this link: https://play.google.com/apps/testing/de.flyingsnail.ipv6droid

**Comment by quite** [comment]
Works for me now, never tried the alpha.

**Comment by pelzvieh** [comment]
Great! Thank you for your patience.
